query{
  __schema {
    types {
      name
      kind
      description
      specifiedByUrl
      fields {
        name
        type {
          name
          kind
          ofType {
            name
            description
            specifiedByUrl
          }
        }
      }
    }
  }
}